# Generated by Django 4.0.6 on 2022-07-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
